Ext.define('Testproject.testproject.web.com.test.view.defaultdomain.CaseUi', {
     "xtype": "caseUi",
     "items": [{
          "xtype": "customdatetimefield",
          "fieldLabel": "From",
          "name": "submitionDate",
          "bindable": "submitionDate",
          "margin": 5,
          "title": "From",
          "itemId": "mneidii",
          "submitFormat": "d-m-Y H:m:s"
     }, {
          "xtype": "customdatetimefield",
          "fieldLabel": "To",
          "name": "tosubmitionDate",
          "bindable": "tosubmitionDate",
          "margin": 5,
          "title": "To",
          "itemId": "olpncdi",
          "submitFormat": "d-m-Y H:m:s"
     }, {
          "xtype": "button",
          "name": "Search",
          "pluginName": "geolocation",
          "isNativeWidget": true,
          "isNativeGeoBtn": true,
          "text": "Search",
          "margin": 5,
          "itemId": "blpdjki",
          "listeners": {
               "click": "onSearchclick"
          }
     }, {
          "xtype": "grids",
          "name": "CaseInfo",
          "title": "Case Info",
          "hiddenName": "Grid",
          "margin": 5,
          "collapseMode": "header",
          "border": true,
          "editTools": false,
          "features": [],
          "plugins": [{
               "ptype": "cellediting",
               "clicksToEdit": 1
          }],
          "columns": [{
               "xtype": "gridcolumn",
               "header": "caseId",
               "dataIndex": "caseId",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "caseId"
          }, {
               "xtype": "gridcolumn",
               "header": "caseNo",
               "dataIndex": "caseNo",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "caseNo"
          }, {
               "xtype": "gridcolumn",
               "header": "caseName",
               "dataIndex": "caseName",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "caseName"
          }, {
               "xtype": "gridcolumn",
               "header": "caseDesc",
               "dataIndex": "caseDesc",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "caseDesc"
          }, {
               "xtype": "gridcolumn",
               "header": "submitionDate",
               "dataIndex": "submitionDate",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "submitionDate"
          }, {
               "xtype": "gridcolumn",
               "header": "createdBy",
               "hidden": true,
               "dataIndex": "createdBy",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "createdBy"
          }, {
               "xtype": "gridcolumn",
               "header": "createdDate",
               "hidden": true,
               "dataIndex": "createdDate",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "createdDate"
          }, {
               "xtype": "gridcolumn",
               "header": "updatedBy",
               "hidden": true,
               "dataIndex": "updatedBy",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "updatedBy"
          }, {
               "xtype": "gridcolumn",
               "header": "updatedDate",
               "hidden": true,
               "dataIndex": "updatedDate",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "updatedDate"
          }, {
               "xtype": "gridcolumn",
               "header": "versionId",
               "hidden": true,
               "dataIndex": "versionId",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "versionId"
          }, {
               "xtype": "gridcolumn",
               "header": "activeStatus",
               "hidden": true,
               "dataIndex": "activeStatus",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "activeStatus"
          }, {
               "xtype": "gridcolumn",
               "header": "txnAccessCode",
               "hidden": true,
               "dataIndex": "txnAccessCode",
               "flex": 1,
               "isColumn": true,
               "parentGridItemId": "pniihbi",
               "name": "txnAccessCode"
          }],
          "itemId": "gdfndii",
          "isRelatedWith": "kfgjbhi",
          "store": {
               "model": "Testproject.testproject.shared.com.test.model.defaultdomain.CaseSubmitionModel",
               "autoLoad": true,
               "autoSync": true,
               "proxy": {
                    "type": "ajax",
                    "url": "secure/CaseSubmition/findAll",
                    "actionMethods": {
                         "read": "GET"
                    },
                    "headers": {
                         "Content-Type": "application/json"
                    },
                    "extraParams": {},
                    "reader": {
                         "type": "json",
                         "rootProperty": "response.data"
                    }
               }
          },
          "tools": [{
               "type": "refresh",
               "tooltip": "Refresh Grid Data",
               "handler": "onGridRefreshClick"
          }]
     }],
     "border": true,
     "autoScroll": true,
     "title": "Form",
     "margin": 5,
     "itemId": "oedioai",
     "dockedItems": [],
     "requires": ["Testproject.testproject.shared.com.test.model.defaultdomain.CaseSubmitionModel", "Testproject.testproject.web.com.test.controller.defaultdomain.CaseUiController", "Testproject.testproject.shared.com.test.viewmodel.defaultdomain.CaseUiViewModel", "Testproject.testproject.shared.com.test.model.defaultdomain.CaseUiModel", "Testproject.view.fw.component.DateTimeField", "Testproject.view.fw.component.DateTimePicker", "Testproject.view.fw.component.Grids"],
     "extend": "Ext.form.Panel",
     "viewModel": "CaseUiViewModel",
     "controller": "CaseUiController"
});