Ext.define('Testproject.testproject.web.com.test.view.defaultdomain.CasePUi', {
     "xtype": "casePUi",
     "items": [{
          "xtype": "textfield",
          "fieldLabel": "caseId",
          "margin": 5,
          "bindable": "caseId",
          "name": "caseId",
          "text": "caseId",
          "fieldName": "caseId",
          "displayName": "caseId",
          "fieldType": "java.lang.String",
          "widget": "textfield",
          "isField": true,
          "itemId": "capooai"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "caseNo",
          "name": "caseNo",
          "margin": 5,
          "bindable": "caseNo",
          "text": "caseNo",
          "fieldName": "caseNo",
          "displayName": "caseNo",
          "fieldType": "java.lang.Integer",
          "widget": "numberfield",
          "isField": true,
          "itemId": "mgbchpi"
     }, {
          "xtype": "textfield",
          "fieldLabel": "caseName",
          "margin": 5,
          "bindable": "caseName",
          "name": "caseName",
          "text": "caseName",
          "fieldName": "caseName",
          "displayName": "caseName",
          "fieldType": "java.lang.String",
          "widget": "textfield",
          "isField": true,
          "itemId": "ipnecli"
     }, {
          "xtype": "textfield",
          "fieldLabel": "caseDesc",
          "margin": 5,
          "bindable": "caseDesc",
          "name": "caseDesc",
          "text": "caseDesc",
          "fieldName": "caseDesc",
          "displayName": "caseDesc",
          "fieldType": "java.lang.String",
          "widget": "textfield",
          "isField": true,
          "itemId": "mpbghdi"
     }, {
          "xtype": "customdatetimefield",
          "fieldLabel": "submitionDate",
          "name": "submitionDate",
          "bindable": "submitionDate",
          "margin": 5,
          "text": "submitionDate",
          "fieldName": "submitionDate",
          "displayName": "submitionDate",
          "fieldType": "java.sql.Timestamp",
          "widget": "customdatetimefield",
          "isField": true,
          "itemId": "loaonki",
          "submitFormat": "d-m-Y H:m:s"
     }],
     "border": true,
     "autoScroll": true,
     "title": "Form",
     "margin": 5,
     "itemId": "eeagjni",
     "dockedItems": [{
          "xtype": "toolbar",
          "dock": "bottom",
          "ui": "footer",
          "isToolBar": true,
          "isDockedItem": true,
          "items": [{
               "xtype": "button",
               "text": "Submit",
               "isSubmitBtn": true,
               "margin": 5,
               "name": "Submit",
               "itemId": "nmcmopi",
               "listeners": {
                    "click": "onSubmitclick"
               }
          }],
          "itemId": "ihhcopi",
          "dockedItems": []
     }],
     "extend": "Ext.form.Panel",
     "requires": ["Testproject.testproject.web.com.test.controller.defaultdomain.CasePUiController", "Testproject.testproject.shared.com.test.viewmodel.defaultdomain.CasePUiViewModel", "Testproject.testproject.shared.com.test.model.defaultdomain.CasePUiModel", "Testproject.view.fw.component.DateTimeField", "Testproject.view.fw.component.DateTimePicker"],
     "viewModel": "CasePUiViewModel",
     "controller": "CasePUiController"
});