Ext.define('Testproject.testproject.shared.com.test.model.defaultcontext.CaseNewQueryModel.CaseNewQueryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "caseId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "caseNo",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "caseName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "caseDesc",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "submitionDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "createdBy",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "createdDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "updatedBy",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "updatedDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "activeStatus",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "txnAccessCode",
          "type": "int",
          "defaultValue": ""
     }]
});